""" Advent of Code 2024
    Day 22: Monkey Market
    Author: Chi-Kit Pao
    julia --optimize=3 Day22.jl
"""

function parse_input(file_name::String)::Vector{Int64}
    lines = []
    return map(s -> parse(Int64, s), readlines(file_name))
end

function process(secret_number::Int64)::Vector{Int64}
    result = [secret_number]
    n = secret_number
    for _ ∈ 1:2000
        n = ((n * 64) ⊻ n) % 16777216
        n = ((n ÷ 32) ⊻ n) % 16777216
        n = ((n * 2048) ⊻ n) % 16777216
        push!(result, n)
    end
    return result
end

function part1(numbers::Vector{Int64})::Int64
    return sum(map(n -> last(process(n)), numbers))
end

all_offer_keys = Set{Tuple{Int64,Int64,Int64,Int64}}()

struct Buyer
    secret_numbers::Vector{Int64}
    prices::Vector{Int64}
    differences::Vector{Int64}
    offers::Dict{Tuple{Int64,Int64,Int64,Int64}, Int64}
end

function Buyer(secret_numbers::Vector{Int64})
    prices = map(n -> n % 10, secret_numbers)
    differences = [((i > 1) ? (prices[i] - prices[i - 1]) : 0)  for i ∈ 1:length(prices)]
    offers = Dict{Tuple{Int64,Int64,Int64,Int64}, Int64}()
    for i ∈ 2:(length(prices) - 3)
        key = Tuple(differences[i:(i+3)])
        if !haskey(offers, key)
            offers[key] = prices[i+3]
            global all_offer_keys
            push!(all_offer_keys, key)
        end
    end
    return Buyer(secret_numbers, prices, differences, offers)
end

function part2(numbers::Vector{Int64})::Int64
    buyers = Vector{Buyer}()
    for number ∈ numbers
        push!(buyers, Buyer(process(number)))
    end

    max_bananas = 0
    for key ∈ all_offer_keys
        bananas = 0
        for buyer ∈ buyers
            try
                bananas += buyer.offers[key]
            catch KeyError
            end
        end
        max_bananas = max(max_bananas, bananas)
    end

    return max_bananas
end

function main()
    numbers = parse_input("input.txt")
    
    println("Question 1: What is the sum of the 2000th secret number generated by each buyer?")
    println("Answer: $(part1(numbers))")
    println("Question 2: What is the most bananas you can get?")
    println("Answer: $(part2(numbers))")

end

@time main()

# Question 1: What is the sum of the 2000th secret number generated by each buyer?
# Answer: 15006633487
# Question 2: What is the most bananas you can get?
# Answer: 1710
#  191.881866 seconds (218.30 M allocations: 8.302 GiB, 0.27% gc time, 0.08% compilation time)
