""" Advent of Code 2024
    Day 22: Monkey Market
    Author: Chi-Kit Pao
    julia --optimize=3 Day22.jl
"""

function parse_input(file_name::String)::Vector{Int64}
    lines = []
    return map(s -> parse(Int64, s), readlines(file_name))
end

function process(secret_number::Int64)
    n = secret_number
    for _ ∈ 1:2000
        n = ((n * 64) ⊻ n) % 16777216
        n = ((n ÷ 32) ⊻ n) % 16777216
        n = ((n * 2048) ⊻ n) % 16777216
    end
    return n
end

function part1(numbers::Vector{Int64})
    return sum(map(n -> process(n), numbers))
end

function main()
    numbers = parse_input("input.txt")
    
    println("Question 1: What is the sum of the 2000th secret number generated by each buyer?")
    println("Answer: $(part1(numbers))")

end

@time main()

# Question 1: What is the sum of the 2000th secret number generated by each buyer?
# Answer: 15006633487
#  0.025215 seconds (9.29 k allocations: 444.938 KiB, 22.11% compilation time)